// 2026 cosmic events calendar.
// Dates cross-checked against Sea & Sky, timeanddate, Royal Observatory
// Greenwich and NASA's Watch the Skies blog. All dates UTC.

export const EVENT_TYPES = {
  eclipse: { label: "Eclipse", color: "#FFB35C" },
  meteors: { label: "Meteor shower", color: "#5CC8FF" },
  opposition: { label: "Opposition", color: "#B49CFF" },
  moon: { label: "Moon event", color: "#EDF2FA" },
  season: { label: "Season marker", color: "#7BE0A8" }
};

export const EVENTS = [
  { date: "2026-01-03", end: "2026-01-04", type: "meteors", title: "Quadrantids peak",
    desc: "Up to 40 meteors/hour from the remains of extinct comet 2003 EH1. Short, sharp peak.", where: "Northern Hemisphere, after midnight" },
  { date: "2026-01-03", type: "moon", title: "Supermoon",
    desc: "The year's first supermoon — the full Moon near its closest point to Earth, looking slightly larger and brighter.", where: "Everywhere" },
  { date: "2026-01-10", type: "opposition", title: "Jupiter at opposition",
    desc: "Earth passes directly between Jupiter and the Sun — the giant planet at its biggest and brightest of the year.", where: "All night, everywhere" },
  { date: "2026-02-17", type: "eclipse", title: "Annular solar eclipse",
    desc: "A 'ring of fire' eclipse — the Moon too far from Earth to fully cover the Sun.", where: "Antarctica" },
  { date: "2026-03-03", type: "eclipse", title: "Total lunar eclipse",
    desc: "The full Moon slides through Earth's shadow and turns deep red for over an hour.", where: "Asia, Australia, Pacific, Americas" },
  { date: "2026-03-20", type: "season", title: "March equinox",
    desc: "Day and night nearly equal everywhere on Earth. Astronomical spring begins in the north.", where: "Everywhere" },
  { date: "2026-04-22", end: "2026-04-23", type: "meteors", title: "Lyrids peak",
    desc: "About 20 meteors/hour from comet Thatcher — debris that left the comet centuries ago.", where: "Northern Hemisphere" },
  { date: "2026-05-02", type: "opposition", title: "Vesta at opposition",
    desc: "The brightest asteroid reaches naked-eye visibility under dark skies — a 500 km rock you can see unaided.", where: "Dark skies, everywhere" },
  { date: "2026-05-05", end: "2026-05-06", type: "meteors", title: "Eta Aquariids peak",
    desc: "Fast meteors from Halley's Comet hitting the atmosphere at 66 km/s.", where: "Best from Southern Hemisphere" },
  { date: "2026-06-21", type: "season", title: "June solstice",
    desc: "The Sun's northernmost point — longest day in the Northern Hemisphere, shortest in the Southern.", where: "Everywhere" },
  { date: "2026-07-31", type: "meteors", title: "Delta Aquariids peak",
    desc: "A steady southern shower of ~20 meteors/hour, the warm-up act for the Perseids.", where: "Best from Southern Hemisphere" },
  { date: "2026-08-12", type: "eclipse", major: true, title: "TOTAL SOLAR ECLIPSE",
    desc: "The big one. Totality sweeps from the Arctic across Greenland and Iceland into Spain at sunset — the first total solar eclipse over mainland Europe since 1999. Partial phases visible across North America, western Europe and Africa.", where: "Greenland · Iceland · Spain" },
  { date: "2026-08-12", end: "2026-08-13", type: "meteors", title: "Perseids peak",
    desc: "The year's most beloved shower, up to 60 meteors/hour — peaking the same night as the total eclipse.", where: "Northern Hemisphere" },
  { date: "2026-08-28", type: "eclipse", title: "Partial lunar eclipse",
    desc: "Earth's shadow takes a deep bite out of the full Moon.", where: "Americas, Europe, Africa" },
  { date: "2026-09-23", type: "season", title: "September equinox",
    desc: "Day and night in balance again. Astronomical autumn begins in the north.", where: "Everywhere" },
  { date: "2026-09-26", type: "opposition", title: "Neptune at opposition",
    desc: "The windiest planet at its closest and brightest — still needs binoculars, but this is the night to try.", where: "All night, everywhere" },
  { date: "2026-10-04", type: "opposition", title: "Saturn at opposition",
    desc: "Saturn at magnitude 0.3, rings on full display in any small telescope.", where: "All night, everywhere" },
  { date: "2026-10-21", end: "2026-10-22", type: "meteors", title: "Orionids peak",
    desc: "Halley's Comet debris, round two — about 20 fast meteors/hour from Orion.", where: "Both hemispheres" },
  { date: "2026-11-17", type: "meteors", title: "Leonids peak",
    desc: "Usually modest, but this is the shower that produced history's great meteor storms.", where: "Both hemispheres" },
  { date: "2026-11-24", type: "moon", title: "Supermoon",
    desc: "First of two consecutive year-end supermoons.", where: "Everywhere" },
  { date: "2026-11-25", type: "opposition", title: "Uranus at opposition",
    desc: "The sideways ice giant at its brightest — binocular territory under dark skies.", where: "All night, everywhere" },
  { date: "2026-12-13", end: "2026-12-14", type: "meteors", title: "Geminids peak",
    desc: "The king of meteor showers: up to 120 multicolored meteors/hour from asteroid 3200 Phaethon.", where: "Both hemispheres" },
  { date: "2026-12-21", type: "season", title: "December solstice",
    desc: "The Sun's southernmost point — the longest night of the year in the north.", where: "Everywhere" },
  { date: "2026-12-24", type: "moon", title: "Supermoon",
    desc: "The year closes with a supermoon on Christmas Eve.", where: "Everywhere" }
];
