export const PLANETS = [
  { name: "Mercury", au: 0.39, tempC: 167, day: "59 Earth days", year: "88 days", moons: 0, size: 0.38, color: "#A8A29E", gravity: 3.7,
    vibe: "A scorched, airless rock where the Sun looks three times larger than from Earth — yet ice hides in its polar shadows.",
    fact: "Despite being the closest planet to the Sun, permanently shadowed craters at its poles hold water ice that never melts." },
  { name: "Venus", au: 0.72, tempC: 464, day: "243 Earth days", year: "225 days", moons: 0, size: 0.95, color: "#E8C07D", gravity: 8.87,
    vibe: "A crushing furnace under permanent acid clouds. The surface pressure would feel like being 900 m underwater.",
    fact: "A day on Venus is longer than its year — and it spins backwards, so the Sun rises in the west." },
  { name: "Earth", au: 1.0, tempC: 15, day: "24 hours", year: "365 days", moons: 1, size: 1.0, color: "#5CC8FF", gravity: 9.81,
    vibe: "The only place in the known universe where anything has ever been alive. Handle with care.",
    fact: "Earth is the only planet we know with active plate tectonics — possibly a key ingredient for long-term habitability." },
  { name: "Mars", au: 1.52, tempC: -65, day: "24.6 hours", year: "687 days", moons: 2, size: 0.53, color: "#E07856", gravity: 3.71,
    vibe: "A cold rust-colored desert with pink skies, blue sunsets, and dust storms that can swallow the whole planet.",
    fact: "Olympus Mons is the largest volcano in the solar system — nearly three times the height of Everest." },
  { name: "Jupiter", au: 5.2, tempC: -110, day: "9.9 hours", year: "11.9 years", moons: 95, size: 11.2, color: "#D9A066", gravity: 24.79,
    vibe: "A striped gas giant so massive that everything else in the solar system could fit inside it — with room to spare.",
    fact: "The Great Red Spot is a storm larger than Earth that has raged for at least 350 years — and it's slowly shrinking." },
  { name: "Saturn", au: 9.58, tempC: -140, day: "10.7 hours", year: "29.5 years", moons: 146, size: 9.45, color: "#E5D5A8", gravity: 10.44, ring: true,
    vibe: "The crown jewel: rings of ice spanning 280,000 km, yet in places only about 10 metres thick.",
    fact: "Saturn is less dense than water — drop it in a big enough ocean and it would float." },
  { name: "Uranus", au: 19.2, tempC: -195, day: "17.2 hours", year: "84 years", moons: 28, size: 4.0, color: "#A8DDE0", gravity: 8.87,
    vibe: "An ice giant knocked onto its side, rolling around the Sun with seasons that last two decades each.",
    fact: "Uranus rotates at a 98° tilt — likely the scar of a colossal ancient collision. Each pole gets 42 years of daylight." },
  { name: "Neptune", au: 30.05, tempC: -200, day: "16.1 hours", year: "165 years", moons: 16, size: 3.88, color: "#6F8FE8", gravity: 11.15,
    vibe: "The windiest world we know — supersonic storms tear through its deep blue clouds at 2,100 km/h.",
    fact: "Neptune was discovered by mathematics before telescopes — its position was predicted from wobbles in Uranus's orbit." }
];
